version: '3.1'

services:
  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_pass
      REDMINE_SECRET_KEY_BASE: redmine_secret
    depends_on:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/alex/navdoc:/repos/navdoc  

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redmine_data:
