# Generated by Django 5.2.1 on 2025-05-29 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=11, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('GESTOR', 'Gestor de Documentos'), ('ENCARGADO', 'Encargado de Puerto')], default='ENCARGADO', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('puerto_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.puerto')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura de Desembarco'), ('MANIFIESTO', 'Manifiesto'), ('CERTIFICADO', 'Certificado de Origen'), ('GUIA', 'Guía de Carga'), ('INSPECCION', 'Informe de Inspección'), ('PERMISO', 'Permiso o Licencia Especial')], max_length=20)),
                ('fecha', models.DateField()),
                ('archivo_pdf', models.FileField(upload_to='documentos/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.puerto')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='PuertoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.puerto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ruta')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('ruta', 'puerto')},
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('VALIDO', 'Válido'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE', 'Pendiente')], max_length=10)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documentocarga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('documento', 'usuario')},
            },
        ),
    ]
