# Generated by Django 5.2.1 on 2025-05-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puerto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='puerto',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puerto',
            name='estado',
            field=models.CharField(default='Activo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentocarga',
            name='tipo',
            field=models.CharField(choices=[('FACTURA', 'Factura de Desembarco'), ('MANIFIESTO', 'Manifiesto'), ('CERTIFICADO', 'Certificado de Origen'), ('GUIA', 'Guía de Carga'), ('INSPECCION', 'Informe de Inspección'), ('PERMISO', 'Permiso o Licencia Especial')], max_length=20),
        ),
    ]
