# Generated by Django 5.2.1 on 2025-05-31 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ruta_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentocarga',
            name='puerto',
        ),
        migrations.RemoveField(
            model_name='documentocarga',
            name='ruta',
        ),
        migrations.AddField(
            model_name='documentocarga',
            name='PuertoRuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.puertoruta'),
        ),
    ]
