# Generated by Django 5.2.1 on 2025-05-31 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_documentocarga_puerto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentocarga',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='documentocarga',
            name='PuertoRuta',
            field=models.ForeignKey(default=75, on_delete=django.db.models.deletion.CASCADE, to='core.puertoruta'),
            preserve_default=False,
        ),
    ]
